# Generated by Django 4.2.11 on 2024-05-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('Rep_P', 'Rep_P'), ('Etud', 'Etud'), ('Invit', 'Invit')], max_length=6)),
                ('pref_p', models.CharField(choices=[('Elect', 'Elect'), ('Therm', 'Therm'), ('None', 'None')], max_length=6)),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Compte',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6)),
                ('p_places', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parking',
            },
        ),
        migrations.CreateModel(
            name='Type_Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_Type', models.CharField(choices=[('Electrique', 'Electrique'), ('Thermique', 'Thermique')], max_length=11)),
                ('t_nb_places', models.IntegerField()),
                ('fk_id_parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cesiapp.parking')),
            ],
            options={
                'verbose_name': 'Type_Place',
                'verbose_name_plural': 'Type_Place',
            },
        ),
    ]
