# Generated by Django 4.2.11 on 2024-05-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cesiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='p_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type_place',
            name='t_nb_places',
            field=models.IntegerField(default=0),
        ),
    ]
